services:
  sqlserver:
    container_name: sqlserver-2022-crudProduto
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      SA_PASSWORD: "SqlServer2022!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  crudProdutoApi:
    container_name: crudProduto-api
    build: ../src
    dockerfile: ./CrudProduto.Api/DockerFile 
    restart: always
    depends_on:  
       -  sqlserver  