services:
  sqlserver:
    container_name: sqlserver-2022-crudProduto
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      SA_PASSWORD: "SqlServer2022!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  crud-produto-api:
    container_name: crudProduto-api
    build: 
        context: ../src
        dockerfile: ./CrudProduto.Api/Dockerfile 
    restart: always
    ports:
      - "5000:8080"
      - "5001:8081"
    depends_on:  
       -  sqlserver  